:database:
  :host: localhost
  :port: 27017
  :name: hive
:site:
  :username: admin
  :password: admin
  :time_zone: -5
:twitter:
  :username: tweetless_pal
:github:
  :username: skalnik
:last_fm:
  :username: mskalnik
